#!/bin/bash
# hakee enigma-boksilta transport streamia halutun sekuntimäärän ja purkaa siitä teksti-tv:n /tmp/vtx/1/txt hakemistoon tekstimuotoon
#
secs=60 #latausaika sekunteina


trap ctrl_c INT

function ctrl_c() {
    echo "** Trapped CTRL-C"
    tapaPidit
    exit
}

function tapaPidit() {
    kill -9 $pid_jpvtx $pid_wget
    echo tapettu $pid_jpvtx $pid_wget
}

rm -rf /tmp/vtx
mkdir -p /tmp/vtx/1 #Tänne tulee vtx-filet
mkdir -p /tmp/vtx/1/txt #Tänne tulee varsinainen teksti
kanava=("http://192.168.1.12:8001/1:0:1:11:1001:20F6:EEEE0000:0:0:0:" "5000")  #yle1 häme
#kanava=("http://192.168.1.12:8001/1:0:16:1D83:1B:46:E080000:0:0:0:" "6751") #svt1 norrbotten
striimi=${kanava[0]}
txtpid=${kanava[1]}

wget -q "$striimi" -O - |./jpvtx $txtpid >/dev/null 2>/dev/null &
pid_jpvtx=$!
pid_wget=`jobs -p`


while [ $secs -gt 0 ]; do
   echo -ne "Latausaikaa jäljellä: $secs sekuntia\033[0K\r"
   sleep 1
   : $((secs--))
done

echo ""
tapaPidit
echo valmis
echo lataukset tekstinä: /tmp/vtx/1/txt/
